ReunionIsland/Controllers/HomeController.cs
using System;
using System.Web.Mvc;
using ReunionIsland.Model;
using ReunionIsland.Web.Tools;

namespace ReunionIsland.Web.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            var model = new ContactViewModel();
            //to test the modal pop up...
            //TempData["shortMessage"] = "Thank you for contacting me!";
            if (TempData["shortMessage"] != null)
            {
                ViewBag.ShowSuccessMessage = TempData["shortMessage"].ToString();
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Contact(ContactViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        ViewBag.ShowSuccessMessage = string.Empty;
                        var contactDetail = new ContactEmail
                        {
                            To = model.ContactEmail,
                            ContactName = model.ContactName,
                            ContactPhoneNumber = model.ContactPhoneNumber,
                            ContactDescription = model.ContactDescription
                        };

                        var result = EmailManager.SendMail(contactDetail);
                        TempData["shortMessage"] = result ? "Thank you for contacting me!" : "Arrf, something wrong happened.";

                    }
                    catch (Exception)
                    {
                        // ignored
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }
    }
}

ReunionIsland/Controllers/LocalisationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReunionIsland.Web.Controllers
{
    public class LocalisationController : Controller
    {
        // GET: Localisation
        public ActionResult Index()
        {
            return View();
        }
    }
}

ReunionIsland/Controllers/PhotoGalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReunionIsland.Web.Controllers
{
    public class PhotoGalleryController : Controller
    {
        // GET: PhotoGallery
        public ActionResult Index()
        {
            return View();
        }
    }
}

ReunionIsland/Views/Home/Index.cshtml
<div class="vNav">
    <ul class="vNav">
        <li>
            <a href="#welcomePanel">
                <div class="label">Accueil</div>
            </a>
        </li>
        <li>
            <a href="#briefDescription">
                <div class="label">Localisation</div>
            </a>
        </li>
        <li>
            <a href="#facilities">
                <div class="label">Sur Place</div>
            </a>
        </li>
        <li>
            <a href="#photoCarroussel">
                <div class="label">La Maison</div>
            </a>
        </li>
        <li>
            <a href="#contactPanelContainer">
                <div class="label">Reserver</div>
            </a>
        </li>
    </ul>
</div>

@*WELCOME PANEL*@
<div class="par" id="welcomePanel" data-stellar-background-ratio="0.5">
    <div class="container">
        <h2 data-aos="zoom-in"
            data-aos-duration="600"
            >Bienvenue sur l'île de la Réunion</h2>
    </div>
</div>

@*BRIEF DESCRIPTION*@
<div class="container-fluid nopadding main" id="briefDescription">
    <div class="row nopadding">
        <div data-aos="zoom-in"
             data-aos-offset="500"
             data-aos-duration="800"
             data-aos-anchor="#briefDescription" class="col-md-6 col-sm-12 briefDescriptionText">
            <div class="container-fluid card">
                <h3>Localisation</h3>
                <div>
                    <p>Venez passer un séjour agréable dans une charmante petite villa, T2 de 85 m2, située dans un jardin tropical privatif, à l’Ermitage les Bains.</p>
                    <p>Le meublé, à 200m du lagon, peut accueillir jusqu’à 5 personnes.</p>
                </div>
                <div>
                    <p><a class="" href="@Url.Action("Index", "Localisation")">Voir la carte</a></p>
                </div>
            </div>
        </div>
        <div data-aos="zoom-in"
             data-aos-offset="500"
             data-aos-duration="800"
             data-aos-anchor="#briefDescription"
             class="col-md-6 col-sm-12 nopadding noDisplayForMobile">
            <img src="/Content/img/frontHome.jpg" class="img-responsive">
        </div>
    </div>
</div>

@*FACILITIES*@
<div class="par" id="facilities" data-stellar-background-ratio="0.5">
    <div class="container">
        <div class="row">
            <h2 data-aos="zoom-in"data-aos-offset="250">
                Sur Place
            </h2>
        </div>
        <div class="row">
            <div class="grid" data-aos="zoom-in" data-aos-offset="250">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 pins">
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 pins">
                        <img src="/Content/img/ConfCall.png" class="img-responsive">
                        <h4>x5</h4>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 pins">
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 pins">
                        <img src="~/Content/img/AirCond.png" class="img-responsive">
                        <h4></h4>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 pins">
                        <img src="~/Content/img/Garage.png" class="img-responsive">
                        <h4>x2</h4>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 pins">
                        <img src="~/Content/img/Shop.png" class="img-responsive">
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 pins">
                        <img src="~/Content/img/BathRoom.png" class="img-responsive">
                        <h4>x2</h4>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 pins">
                        <img src="~/Content/img/SleepingRoom.png" class="img-responsive">
                        <h4>x6</h4>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 pins">
                        <img src="~/Content/img/Wifi.png" class="img-responsive">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@*Carroussel*@
<div class="container-fluid nopadding main" id="photoCarroussel">
    <div class="row nopadding">
        <div data-aos="zoom-in"
             data-aos-offset="500"
             data-aos-duration="800"
             data-aos-anchor="#photoCarroussel" class="col-md-6 col-sm-12 noDisplayForMobile carroussel">
            <ul class="rslides">
                <li><img src="../../Content/img/outdoor01.JPG" class="img-responsive" alt=""></li>
                <li><img src="../../Content/img/outdoor02.JPG" class="img-responsive" alt=""></li>
                <li><img src="../../Content/img/outdoor03.JPG" class="img-responsive" alt=""></li>
                <li><img src="../../Content/img/outdoor04.JPG" class="img-responsive" alt=""></li>
                <li><img src="../../Content/img/bathRoom.JPG" class="img-responsive" alt=""></li>
                <li><img src="../../Content/img/bedRoom01.JPG" class="img-responsive" alt=""></li>
                <li><img src="../../Content/img/bedRoom02.JPG" class="img-responsive" alt=""></li>
                <li><img src="../../Content/img/bedRoom03.JPG" class="img-responsive" alt=""></li>
                <li><img src="../../Content/img/kitchen.JPG" class="img-responsive" alt=""></li>
            </ul>
        </div>
        <div data-aos="zoom-in"
             data-aos-offset="500"
             data-aos-duration="800"
             data-aos-anchor="#photoCarroussel" class="col-md-6 col-sm-12">
            <div class="container-fluid card">
                <h3>A la maison</h3>
                <br />
                <div id="para">
                    <p>Entièrement rénovée, bien équipée, séjour et chambre climatisés; vous trouverez dans cette location, tout ce dont vous aurez besoin pour votre confort de vie (box internet indépendante orange, bouquet TV, lave-linge, linge de maison, dressing, placards , barbecue …).</p>
                    <p>Les places de parking sont sécurisées.</p>
                </div>
                <br />
                <div id="link">
                    <p><a class="toLocationDetails" href="@Url.Action("Index", "PhotoGallery")">Plus de détails</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

@*CONTACT*@
<div id="contactPanelContainer" class="par contactPanel" data-stellar-background-ratio="0.5">
    <div class="container">
        <div data-aos="zoom-in"
                data-aos-offset="500">
            <h2>Contactez nous !</h2>
        </div>
        <div data-aos="flip-down"
                data-aos-offset="400"
                class="col-lg-12">
            @Html.Partial("~/Views/Home/_Contact.cshtml")
        </div>
    </div>
</div>

@*SPINNER LOADING*@
<div id="loading">
    <div id="loadingcontent">
        <p id="loadingspinner">
            Currently sending your information...
        </p>
    </div>
</div>

@*MODAL POPUP*@
<div id="successModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="successModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="text-center">
                <div class="modal-header">
                    <img id="imageresource" src="../Content/img/contact-us.png">
                    <h3>Your WebDev Agency</h3>
                </div>
                <div>

                </div>
            </div>
            <div class="modal-body">
                <h4 id="showSuccessMessage" class="modal-title text-center">@Html.Raw(ViewBag.ShowSuccessMessage)</h4>
            </div>
            <div class="modal-footer">
                <div class="text-center">
                    <div class="btn-group btn-group-sm">
                        <button type="button" class="btn btn-sm btn-primary btn-raised" data-dismiss="modal">Continue on the site...</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ReunionIsland/Views/Home/_Contact.cshtml
@using ReunionIsland.Web.Controllers
@model ReunionIsland.Model.ContactViewModel

<div id="ContactForm">
    @using (Html.BeginForm("Contact", "Home", FormMethod.Post, new { id = "frmContact" }))
    { 
        <div class="form-group row">
            <div class="col-md-12">
                @Html.EditorFor(model => model.ContactName, new {htmlAttributes = new {@class = "col-md-8 form-control", style = "min-width: 100%", placeholder = "Contact Name" } })
                @Html.ValidationMessageFor(model => model.ContactName, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-6">
                @Html.EditorFor(model => model.ContactEmail, new {htmlAttributes = new {@class = "col-md-8 form-control", style = "min-width: 100%", placeholder = "Contact eMail"}})
                @Html.ValidationMessageFor(model => model.ContactEmail, "", new {@class = "text-danger"})
            </div>
            <div class="col-md-6">
                @Html.EditorFor(model => model.ContactPhoneNumber, new { htmlAttributes = new { @class = "col-md-8 form-control", style = "min-width: 100%", placeholder = "Contact Phone Number" } })
                @Html.ValidationMessageFor(model => model.ContactPhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-12">
               @Html.TextAreaFor(model => model.ContactDescription, new { @class = "form-control", style = "min-width: 100%", rows = "5", maxlength = "1000", placeholder = "Describe your project" })
                @Html.ValidationMessageFor(model => model.ContactDescription, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="pull-right">
            <button type="submit" id="submitContact" class="btn btn-primary">Submit</button>
        </div>
    }
</div>

ReunionIsland/Views/Localisation/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div id="LocalisationPanel">
    <div class="container">
        <h2>Localisation</h2>
        <div id="map"></div>
    </div>
</div>

<div id="laReunionPanel">
    <div class="container">
        <h2>Découvrez L'île de la Réunion</h2>
    </div>
</div>

ReunionIsland/Views/PhotoGallery/Index.cshtml
<div id="welcomePhotoGalleryPanel">
    <div class="container">
        <h2>Photos</h2>
    </div>
</div>

<div id="photoGalleryPanel">
    <div class="container">
        <div id="gallery">
            <img alt="Image 1 Title" src="/Content/img/outdoor01.JPG"
                    data-image="/Content/img/outdoor01.JPG"
                    data-description="Image 1 Description">
            <img alt="Image 2 Title" src="/Content/img/outdoor02.JPG"
                 data-image="/Content/img/outdoor02.JPG"
                 data-description="Image 2 Description">
            <img alt="Image 1 Title" src="/Content/img/outdoor01.JPG"
                 data-image="/Content/img/outdoor01.JPG"
                 data-description="Image 1 Description">
            <img alt="Image 2 Title" src="/Content/img/outdoor02.JPG"
                 data-image="/Content/img/outdoor02.JPG"
                 data-description="Image 2 Description">
            <img alt="Image 1 Title" src="/Content/img/outdoor01.JPG"
                 data-image="/Content/img/outdoor01.JPG"
                 data-description="Image 1 Description">
            <img alt="Image 2 Title" src="/Content/img/outdoor02.JPG"
                 data-image="/Content/img/outdoor02.JPG"
                 data-description="Image 2 Description">
            <img alt="Image 1 Title" src="/Content/img/outdoor01.JPG"
                 data-image="/Content/img/outdoor01.JPG"
                 data-description="Image 1 Description">
            <img alt="Image 2 Title" src="/Content/img/outdoor02.JPG"
                 data-image="/Content/img/outdoor02.JPG"
                 data-description="Image 2 Description">
            <img alt="Image 1 Title" src="/Content/img/outdoor01.JPG"
                 data-image="/Content/img/outdoor01.JPG"
                 data-description="Image 1 Description">
            <img alt="Image 2 Title" src="/Content/img/outdoor02.JPG"
                 data-image="/Content/img/outdoor02.JPG"
                 data-description="Image 2 Description">
        </div>
    </div>
</div>

ReunionIsland/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="../../Content/img/comput.png">
    <title>La Réunion | Location Saisonnière</title>
    @*CSS Bundle*@
    <link href="https://fonts.googleapis.com/css?family=Hind" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    @Styles.Render("~/bundles/css")

</head>
<body>
<div class="navbar navbar-inverse">
    <div class="container">
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                @*<li>
                    <a class="effectMenu" href="#welcomePanel">Accueil</a>
                </li>*@
                <li>
                    <a class="active effectMenu" href="#briefDescription">Localisation</a>
                </li>
                <li>
                    <a class="effectMenu" href="#facilities">Sur Place</a>
                </li>
                <li>
                    <a class="effectMenu" href="#photoCarroussel">La Maison</a>
                </li>
                <li>
                    <a class="effectMenu" href="#contactPanelContainer">Reserver</a>
                </li>
            </ul>
        </div>
    </div>
</div>

@RenderBody()
<footer>
    <div class="container">
        <p>&copy; @DateTime.Now.Year - www.VisitLaReunion.com</p>
    </div>
</footer>

@*JS Bundle*@
@Scripts.Render("~/bundles/js")

</body>
</html>


@***************@
@*Effect Script*@
@***************@
<script>
    //ON HOVER
    function animationHover(element, animation) {
        element = $(element);
        element.hover(
            function() {
                element.addClass('animated ' + animation);
            },
            function() {
                //wait for animation to finish before removing classes
                window.setTimeout(function() {
                        element.removeClass('animated ' + animation);
                    },
                    2000);
            });
    }

    //ON READY
    function animationIntro(element, animation) {
        element = $(element);
        element.addClass('animated ' + animation);
        window.setTimeout(function() {
                element.removeClass('animated ' + animation);
            },
            2000);
    }
  
    //HOVER
    //effect - Hover for Menu
    $(document)
        .ready(function() {
            $('.effectMenu')
                .each(function() {
                    animationHover(this, 'swing');
                });
        });
</script>

@*CAROUSSEL PHOTO GALLERY (auto run)*@
<script>
  $(function() {
    $(".rslides").responsiveSlides();
  });
</script>

@*MODAL POP UP*@
<script>
    $(document)
        .ready(function() {
            // Show Update Success modal popup
            if ($('#showSuccessMessage').text().length > 0) {
                $('#successModal').modal({ backdrop: 'static' });
            }
        });
</script>

@*SPINNER LOADING - Submit contact details*@
<script>
    $(function () {
        $("#submitContact").click(function () {
            debugger;
            if ($("#frmContact").valid()) {
                $("#loading").fadeIn();
                var opts = {
                    lines: 12, // The number of lines to draw
                    length: 7, // The length of each line
                    width: 4, // The line thickness
                    radius: 10, // The radius of the inner circle
                    color: '#000', // #rgb or #rrggbb
                    speed: 1, // Rounds per second
                    trail: 60, // Afterglow percentage
                    shadow: false, // Whether to render a shadow
                    hwaccel: false // Whether to use hardware acceleration
                };
                var target = document.getElementById('loading');
                var spinner = new Spinner(opts).spin(target);
            }
        });
    });
</script>

@*Google Map for house location*@
<script>
    function initMap() {
        var uluru = {lat: -25.363, lng: 131.044};
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 4,
            center: uluru
        });
        var marker = new google.maps.Marker({
            position: uluru,
            map: map
        });
    }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDbunbKx8vsHKrNWwhJlsZmSCDawGDeqY8&callback=initMap">
</script>

@*AOS special effect framework*@
<script>
    AOS.init({
        //disable: window.innerWidth < 1024
    });
</script>

@*STELLAR*@
<script>
    $(document)
        .ready(function() {
            $.stellar({
                horizontalScrolling: false,
                responsive: true
            });
        });
</script>

@*Smoothly Scrolling*@
<script>
    $('a[href*="#"]:not([href="#"])').click(function () {
        if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') && location.hostname == this.hostname) {
            var target = $(this.hash);
            target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
            if (target.length) {
                $('html, body').animate({
                    scrollTop: target.offset().top
                }, 1000);
                return false;
            }
        }
    });
</script>

@*Vertical side scroll*@
<script>
    $(document).ready(function ($) {
        var parPosition = [];
        $('.par').each(function () {
            parPosition.push($(this).offset().top);
        });

        $('a').click(function () {
            $('html, body').animate({
                scrollTop: $($.attr(this, 'href')).offset().top
            }, 500);
            return false;
        });

        $('.vNav ul li a').click(function () {
            $('.vNav ul li a').removeClass('active');
            $(this).addClass('active');
        });

        $('.vNav a').hover(function () {
            $(this).find('.label').show();
        }, function () {
            $(this).find('.label').hide();
        });

        $(document).scroll(function () {
            var position = $(document).scrollTop(),
                index;
            for (var i = 0; i < parPosition.length; i++) {
                if (position <= parPosition[i]) {
                    index = i;
                    break;
                }
            }
            $('.vNav ul li a').removeClass('active');
            $('.vNav ul li a:eq(' + index + ')').addClass('active');
        }).scroll();

        $('.vNav ul li a').click(function () {
            $('.vNav ul li a').removeClass('active');
            $(this).addClass('active');
        });
    });
</script>